export const DATA = 'DATA';

export const SEARCH_ASYNC_ENTITIES = 'SEARCH_ASYNC_ENTITIES';

export const SET_ID_USER = 'SET_ID_USER';

export const SET_USER = 'SET_USER';

export const SET_MENU = 'SET_MENU';

export const SET_MENU_CONTAINER = 'SET_MENU_CONTAINER';

export const ADD_ASSIGNEMENT_USER = 'ADD_ASSIGNEMENT_USER';

export const ADD_ALL_ASSIGNEMENT_USER = 'ADD_ALL_ASSIGNEMENT_USER';

export const DELETE_ALL_ASSIGNEMENT_USER = 'DELETE_ALL_ASSIGNEMENT_USER';

export const REMOVE_ALL_ASSIGNEMENT_USER = 'REMOVE_ALL_ASSIGNEMENT_USER';

export const DELETE_ASSIGNEMENT_USER = 'DELETE_ASSIGNEMENT_USER';

export const DELETE_MOBILE_SELLERS = 'DELETE_MOBILE_SELLERS';

export const EDIT_ASSIGNEMENT_USER = 'EDIT_ASSIGNEMENT_USER';

export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';

export const SET_INITIAL_DATA_QUESTIONER_QUESTIONARY = 'SET_INITIAL_DATA_STATE_QUESTIONER_QUESTIONARY';

export const SET_INITIAL_DATA_TYPES_SELLER = 'SET_INITIAL_DATA_STATE_TYPES_SELLER';

export const SAVE_MOBILE_LIST_AUX = 'SAVE_MOBILE_LIST_AUX';

export const SAVE_MOBILE_ASSIGNED_LIST_AUX = 'SAVE_MOBILE_ASSIGNED_LIST_AUX';

export const DELETE_MOBILE_LIST_AUX = 'DELETE_MOBILE_LIST_AUX';

export const DELETE_MOBILE_ASSIGNED_LIST_AUX = 'DELETE_MOBILE_ASSIGNED_LIST_AUX';

export const ADD_MOBILE_SELLERS = "ADD_MOBILE_SELLERS";

export const ADD_MOBILE_SELLER = "ADD_MOBILE_SELLER";

export const EDIT_QUERY_TEXT_MOBILE_SELLER_LIST = 'EDIT_QUERY_TEXT_MOBILE_SELLER_LIST';

export const EDIT_QUERY_TEXT_MOBILE_SELLER_ASSIGNED_LIST = 'EDIT_QUERY_TEXT_MOBILE_SELLER_ASSIGNED_LIST';

export const EDIT_QUERY_TEXT_QUESTIONARY_ASSIGNED_LIST = 'EDIT_QUERY_TEXT_QUESTIONARY_ASSIGNED_LIST';

export const CREATE_QUESTIONARY = 'CREATE_QUESTIONARY';

export const DELETE_QUESTIONARY = 'DELETE_QUESTIONARY';

export const FILL_OUT_QUESTIONNAIRE = 'FILL_OUT_QUESTIONNAIRE';

export const CREATE_QUESTION = 'CREATE_QUESTION';

export const DELETE_QUESTION = 'DELETE_QUESTION';

export const FILL_OUT_QUESTIONS_ALL = 'FILL_OUT_QUESTION';

export const CREATE_QUESTION_OPTION = 'CREATE_QUESTION_OPTION';

export const DELETE_QUESTION_OPTION = 'DELETE_QUESTION_OPTION';

export const FILL_OUT_QUESTION_OPTION_ALL = 'FILL_OUT_QUESTION_OPTION';

export const CREATE_QUESTIONARY_RANGE = 'CREATE_QUESTIONARY_RANGE';

export const DELETE_QUESTIONARY_RANGE = 'DELETE_QUESTIONARY_RANGE';

export const FILL_OUT_QUESTIONARY_RANGE_ALL = 'FILL_OUT_QUESTIONARY_RANGE_ALL';

export const CHANGE_ID_EXISTING_QUESTIONARY = 'CHANGE_ID_EXISTING_QUESTIONARY';

export const GET_ALL_DEPARTAMENTS = 'GET_ALL_DEPARTAMENTS';

export const GET_ALL_BRANCHES = 'GET_ALL_BRANCHES';

/* Filter advance*/

export const ADD_PARAM_FILTER_MOBILE_SELLER_TYPE = 'ADD_PARAM_FILTER_MOBILE_SELLER_TYPE';

export const ADD_PARAM_FILTER_MOBILE_SELLER_BRANCH = 'ADD_PARAM_FILTER_MOBILE_SELLER_BRANCH';

export const CONCAT_FILTER_MOBILE_SELLER_BRANCH = 'CONCAT__FILTER_MOBILE_SELLER_BRANCH';

export const ADD_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_TYPE = 'ADD_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_TYPE';

export const ADD_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH = 'ADD_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH';

export const CONCAT_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH = 'CONCAT__FILTER_MOBILE_SELLER_ASSIGNED_BRANCH';

export const DELETE_PARAM_FILTER_MOBILE_SELLER_TYPE = 'DELETE_PARAM_FILTER_MOBILE_SELLER_TYPE';

export const DELETE_PARAM_FILTER_MOBILE_SELLER_BRANCH = 'DELETE_PARAM_FILTER_MOBILE_SELLER_BRANCH';

export const DELETE_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_TYPE = 'DELETE_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_TYPE';

export const DELETE_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH = 'DELETE_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH';

export const CLEAN_FILTER = 'CLEAN_FILTER';

export const CHANGE_OPERATION_ID_BRANCH_SELLER = 'CHANGE_OPERATION_ID_BRANCH_SELLER';

export const CHANGE_OPERATION_ID_BRANCH_SELLER_ASSIGNED = 'CHANGE_OPERATION_ID_BRANCH_SELLER_ASSIGNED';