export const DATA = 'DATA';

export const SEARCH_ASYNC_ENTITIES = 'SEARCH_ASYNC_ENTITIES';

export const SET_ID_USER = 'SET_ID_USER';

export const SET_USER = 'SET_USER';

export const SET_MENU = 'SET_MENU';

export const SET_MENU_CONTAINER = 'SET_MENU_CONTAINER';

export const ADD_ASSIGNEMENT_USER = 'ADD_ASSIGNEMENT_USER';

export const ADD_ALL_ASSIGNEMENT_USER = 'ADD_ALL_ASSIGNEMENT_USER';

export const DELETE_ALL_ASSIGNEMENT_USER = 'DELETE_ALL_ASSIGNEMENT_USER';

export const REMOVE_ALL_ASSIGNEMENT_USER = 'REMOVE_ALL_ASSIGNEMENT_USER';

export const DELETE_ASSIGNEMENT_USER = 'DELETE_ASSIGNEMENT_USER';

export const DELETE_MOBILE_SELLERS = 'DELETE_MOBILE_SELLERS';

export const EDIT_ASSIGNEMENT_USER = 'EDIT_ASSIGNEMENT_USER';

export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';

export const SET_INITIAL_DATA_QUESTIONER_QUESTIONARY = 'SET_INITIAL_DATA_STATE_QUESTIONER_QUESTIONARY';

export const SET_INITIAL_DATA_TYPES_SELLER = 'SET_INITIAL_DATA_STATE_TYPES_SELLER';

export const SAVE_MOBILE_LIST_AUX = 'SAVE_MOBILE_LIST_AUX';

export const SAVE_MOBILE_ASSIGNED_LIST_AUX = 'SAVE_MOBILE_ASSIGNED_LIST_AUX';

export const DELETE_MOBILE_LIST_AUX = 'DELETE_MOBILE_LIST_AUX';

export const DELETE_MOBILE_ASSIGNED_LIST_AUX = 'DELETE_MOBILE_ASSIGNED_LIST_AUX';

export const ADD_MOBILE_SELLERS = "ADD_MOBILE_SELLERS";

export const ADD_MOBILE_SELLER = "ADD_MOBILE_SELLER";

export const EDIT_QUERY_TEXT_MOBILE_SELLER_LIST = 'EDIT_QUERY_TEXT_MOBILE_SELLER_LIST';

export const EDIT_QUERY_TEXT_MOBILE_SELLER_ASSIGNED_LIST = 'EDIT_QUERY_TEXT_MOBILE_SELLER_ASSIGNED_LIST';

export const EDIT_QUERY_TEXT_QUESTIONARY_ASSIGNED_LIST = 'EDIT_QUERY_TEXT_QUESTIONARY_ASSIGNED_LIST';

export const CREATE_QUESTIONARY = 'CREATE_QUESTIONARY';

export const DELETE_QUESTIONARY = 'DELETE_QUESTIONARY';

export const FILL_OUT_QUESTIONNAIRE = 'FILL_OUT_QUESTIONNAIRE';

export const CREATE_QUESTION = 'CREATE_QUESTION';

export const DELETE_QUESTION = 'DELETE_QUESTION';

export const FILL_OUT_QUESTIONS_ALL = 'FILL_OUT_QUESTION';

export const CREATE_QUESTION_OPTION = 'CREATE_QUESTION_OPTION';

export const DELETE_QUESTION_OPTION = 'DELETE_QUESTION_OPTION';

export const FILL_OUT_QUESTION_OPTION_ALL = 'FILL_OUT_QUESTION_OPTION';

export const CREATE_QUESTIONARY_RANGE = 'CREATE_QUESTIONARY_RANGE';

export const DELETE_QUESTIONARY_RANGE = 'DELETE_QUESTIONARY_RANGE';

export const FILL_OUT_QUESTIONARY_RANGE_ALL = 'FILL_OUT_QUESTIONARY_RANGE_ALL';

export const CHANGE_ID_EXISTING_QUESTIONARY = 'CHANGE_ID_EXISTING_QUESTIONARY';

export const GET_ALL_DEPARTAMENTS = 'GET_ALL_DEPARTAMENTS';

export const GET_ALL_BRANCHES = 'GET_ALL_BRANCHES';

/* Filter advance*/

export const ADD_PARAM_FILTER_MOBILE_SELLER_TYPE = 'ADD_PARAM_FILTER_MOBILE_SELLER_TYPE';

export const ADD_PARAM_FILTER_MOBILE_SELLER_BRANCH = 'ADD_PARAM_FILTER_MOBILE_SELLER_BRANCH';

export const CONCAT_FILTER_MOBILE_SELLER_BRANCH = 'CONCAT__FILTER_MOBILE_SELLER_BRANCH';

export const ADD_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_TYPE = 'ADD_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_TYPE';

export const ADD_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH = 'ADD_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH';

export const CONCAT_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH = 'CONCAT__FILTER_MOBILE_SELLER_ASSIGNED_BRANCH';

export const DELETE_PARAM_FILTER_MOBILE_SELLER_TYPE = 'DELETE_PARAM_FILTER_MOBILE_SELLER_TYPE';

export const DELETE_PARAM_FILTER_MOBILE_SELLER_BRANCH = 'DELETE_PARAM_FILTER_MOBILE_SELLER_BRANCH';

export const DELETE_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_TYPE = 'DELETE_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_TYPE';

export const DELETE_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH = 'DELETE_PARAM_FILTER_MOBILE_SELLER_ASSIGNED_BRANCH';

export const CLEAN_FILTER = 'CLEAN_FILTER';

export const CHANGE_OPERATION_ID_BRANCH_SELLER = 'CHANGE_OPERATION_ID_BRANCH_SELLER';

export const CHANGE_OPERATION_ID_BRANCH_SELLER_ASSIGNED = 'CHANGE_OPERATION_ID_BRANCH_SELLER_ASSIGNED';

export const SET_SYSTEM_TYPES = 'SET_SYSTEM_TYPES';

export const SET_REACH_TYPES = 'SET_REACH_TYPES';

export const SET_QUESTIONNAIRE_STATUS = 'SET_QUESTIONNAIRE_STATUS';

export const UPDATE_MARKED_OPTIONS = 'UPDATE_MARKED_OPTIONS';

export const SET_MARKED_OPTIONS = 'SET_MARKED_OPTIONS';

export const TRIED_TO_SAVE = 'TRIED_TO_SAVE';

export const SAVE_CLIENT = 'SAVE_CLIENT';

export const SAVE_INTERVIEWED_NAME = 'SAVE_INTERVIEWED_NAME';

export const IS_SAVING_ANSWER = 'IS_SAVING_ANSWER';

export const SET_STATUS_TYPES = 'SET_STATUS_TYPES';

/* Answers Page*/

export const GET_ANSWERS = 'GET_ANSWERS';
export const SET_ANSWERS = 'SET_ANSWERS';
export const GET_QUESTIONNARIE_ANSWER = 'GET_QUESTIONNARIE_ANSWER';
export const SET_QUESTIONNARIE_ANSWER = 'SET_QUESTIONNARIE_ANSWER';

/* GENERATION EXPENSES*/
export const LOAD_INPUT_BASE_INFORMATION = 'LOAD_INPUT_BASE_INFORMATION';
export const LOAD_COST_BASE_INFORMATION = 'LOAD_COST_BASE_INFORMATION';
export const GENERATION_EXPENSES = 'GENERATION_EXPENSES';
export const CHANGE_ERROR_REQUEST = 'CHANGE_ERROR_REQUEST';
export const CLEAN_REQUEST_EXECUTE = "CLEAN_REQUEST_EXECUTE";

/* Create Center Master And Cost*/
export const LOAD_BASE_DATA_CREATE_CENTER_MASTER_AND_COST = 'LOAD_BASE_DATA_CREATE_CENTER_MASTER_AND_COST';
export const CHANGE_ERROR_REQUEST_CCMAC= 'CHANGE_ERROR_REQUEST_CCMAC';
export const CLEAN_REQUEST_CCMAC = "CLEAN_REQUEST_CCMAC";

/*Center Cost Condition*/
export const DELETE_CONDITION_CENTER_MASTER = 'DELETE_CONDITION_CENTER_MASTER';
export const UPDATE_CONDITION_CENTER_MASTER = 'UPDATE_CONDITION_CENTER_MASTER';
export const CREATE_CONDITION_CENTER_MASTER = 'CREATE_CONDITION_CENTER_MASTER';
export const FILTER_CENTER_COST_CONDITION = "FILTER_CENTER_COST_CONDITION";
export const CHANGE_ERROR_REQUEST_BI = 'CHANGE_ERROR_REQUEST_BI';
export const CLEAN_REQUEST_BI = "CLEAN_REQUEST_BI";

/* Period And Account Registration*/
export const GET_DATA_CREATE_ACCOUNT_PERIOD = 'GET_DATA_CREATE_ACCOUNT_PERIOD';
export const LOAD_INIT_DATA_ACCOUNT_PERIOD_REGISTRATION_BI = 'LOAD_INIT_DATA__ACCOUNT_PERIOD_REGISTRATION_BI';
export const CREATE_ACCOUNT_PERIOD_BI = 'CREATE_ACCOUNT_PERIOD_BI';
export const UPDATE_ACCOUNT_PERIOD_BI = 'UPDATE_ACCOUNT_PERIOD_BI';
export const DELETE_ACCOUNT_PERIOD_BI = 'DELETE_ACCOUNT_PERIOD_BI';
export const CHANGE_ERROR_REQUEST_ACCOUNT_PERIOD_BI = 'CHANGE_ERROR_REQUEST_ACCOUNT_PERIOD_BI';
export const CLEAN_REQUEST_ACCOUNT_PERIOD_BI = 'CLEAN_REQUEST_ACCOUNT_PERIOD_BI';

/* Exchange Rate */
export const GET_INITIAL_DATA_EXCHANGE_RATE_BI = "GET_INITIAL_DATA_EXCHANGE_RATE_BI";
export const CREATE_EXCHANGE_RATE_BI = "CREATE_EXCHANGE_RATE_BI";
export const UPDATE_EXCHANGE_RATE_BI = "UPDATE_EXCHANGE_RATE_BI";
export const DELETE_EXCHANGE_RATE_BI = "DELETE_EXCHANGE_RATE_BI";
export const CHANGE_ERROR_EXCHANGE_RATE_BI = "CHANGE_ERROR_EXCHANGE_RATE_BI";
export const CLEAN_REQUEST_EXCHANGE_RATE_BI = "CLEAN_REQUEST_EXCHANGE_RATE_BI";

/* OperatingAccounts*/
export const GET_INITIAL_DATA_OPERATING_ACCOUNTS_BI = "GET_INITIAL_DATA_OPERATING_ACCOUNTS_BI";
export const CREATE_OPERATING_ACCOUNTS_BI = "CREATE_OPERATING_ACCOUNTS_BI";
export const UPDATE_OPERATING_ACCOUNTS_BI = "UPDATE_OPERATING_ACCOUNTS_BI";
export const DELETE_OPERATING_ACCOUNTS_BI = "DELETE_OPERATING_ACCOUNTS_BI";
export const CHANGE_ERROR_OPERATING_ACCOUNTS_BI = "CHANGE_ERROR_OPERATING_ACCOUNTS_BI";
export const CLEAN_REQUEST_OPERATING_ACCOUNTS_BI = "CLEAN_REQUEST_OPERATING_ACCOUNTS_BI";

/**
 * CONCEPT
 */
export const GET_ALL_CONCEPTS = 'GET_ALL_CONCEPTS';
export const DELETE_CONCEPT_BI = "DELETE_CONCEPT_BI";
export const CREATE_CONCEPT_BI = "CREATE_CONCEPT_BI";
export const UPDATE_CONCEPT_BI = "UPDATE_CONCEPT_BI";
/**
 * TYPE
 */
export const GET_ALL_TYPES = 'GET_ALL_TYPES';
export const DELETE_TYPES_BI = "DELETE_TYPES_BI";
export const CREATE_TYPES_BI = "CREATE_TYPES_BI";
export const UPDATE_TYPES_BI = "UPDATE_TYPES_BI";
/*Parameters*/
export const GET_ALL_PARAMETERS = "GET_ALL_PARAMETERS";
export const CHANGE_ERROR_REQUEST_PARAMETER_BI = 'CHANGE_ERROR_REQUEST_PARAMETER_BI';
export const CLEAN_REQUEST_PARAMETER_BI = "CLEAN_REQUEST_PARAMETER_BI";
export const CHANGE_STATE = 'CHANGE_STATE';
/*Job ETL*/
export const JOB_EXECUTE = "JOB_EXECUTE";
export const GET_DATA_PARAMETERS = "GET_DATA_PARAMETERS";
