
export const DATA = 'DATA';

export const SEARCH_ASYNC_ENTITIES = 'SEARCH_ASYNC_ENTITIES';

export const SET_ID_USER = 'SET_ID_USER';

export const SET_MENU_CONTAINER = 'SET_MENU_CONTAINER';

export const ADD_ASSIGNEMENT_USER = 'ADD_ASSIGNEMENT_USER';

export const DELETE_ALL_ASSIGNEMENT_USER = 'DELETE_ALL_ASSIGNEMENT_USER';

export const DELETE_ASSIGNEMENT_USER = 'DELETE_ASSIGNEMENT_USER';

export const EDIT_ASSIGNEMENT_USER = 'EDIT_ASSIGNEMENT_USER';

export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';

export const SAVE_MOBILE_LIST_AUX = 'SAVE_MOBILE_LIST_AUX';

export const DELETE_MOBILE_LIST_AUX = 'DELETE_MOBILE_LIST_AUX';

export const ADD_MOBILE_SELLERS = "ADD_MOBILE_SELLERS";

export const ADD_MOBILE_SELLER = "ADD_MOBILE_SELLER";

export const EDIT_QUERY_TEXT_MOBILE_SELLER_LIST = 'EDIT_QUERY_TEXT_MOBILE_SELLER_LIST';
export const EDIT_QUERY_TEXT_MOBILE_SELLER_ASSIGNED_LIST = 'EDIT_QUERY_TEXT_MOBILE_SELLER_ASSIGNED_LIST';
export const EDIT_QUERY_TEXT_QUESTIONARY_ASSIGNED_LIST = 'EDIT_QUERY_TEXT_QUESTIONARY_ASSIGNED_LIST';